language: haskell
dist: trusty
sudo: false

addons:
  apt:
    packages:
    - equivs
    - python

env:
  global:
    - PATH=$HOME/.local/bin:$PATH
  matrix:
    - TARGET=pandoc
    - TARGET=texlive

before_install:
  - mkdir -p $HOME/.local/bin
  - export COMMIT_TARGET="$(git log --format=%B --no-merges -n 1 | grep -E "\[build .+\]" | sed 's/.*\[build \(.*\)\].*/\1/')"
  - "if [ ! -z $COMMIT_TARGET ]; then if [ $COMMIT_TARGET != $TARGET ]; then export TARGET=''; fi; fi"

install:
  - "[ -z $TRAVIS_TAG ] && exit 0 || true"
  - ./install

script:
  - "[ -z $TRAVIS_TAG ] || ./build"

cache:
  directories:
  - $HOME/.stack

before_deploy:
  - "[ -z $TRAVIS_TAG ] || [ -z $TARGET ] || curl -s https://api.github.com/repos/yihui/ubuntu-bin/releases/latest | python delete.py $TARGET"

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GH_TOKEN
  local_dir: ~/.local/bin
  on:
    branch: master
