language: haskell
dist: trusty
sudo: false
addons:
  apt:
    packages:
    - equivs
    - python
env:
  global:
  - PATH=$HOME/.local/bin:$PATH
  - secure: NTIhA0tuWsk6k+SecW8WwOu0i6BBb/h+MPAn4ZvfpIb7zs4F3BQnVdW+XEdGB7Th5POQg0TT5vtuD7rDELRC6qKrtc+z4xIgkMSsR/6iPrr0vUDU6Mq0DeRNiVCW8xGyTW0XysiMFUMWOyceusTn00UlXQ5ucIOL0mmHNwR4U7SrmmXFBxBgZDXJwZ4jpCAt2S/rzGNTBzTNjSALfhXrUC8GcC0k9vjogG5+NrLhSKKjF6UBa7jWYJlneBILUwaUIsgU5dVLqxYQbSrlEpja5DVh9FUnq8x+OjF4B61YrCikAVyRnw6tE2nC6elTOmrOji01R1DKkyImNwvvmRwNYGVSt0cIheYNGaHXNpLOxe733W9jIiAsa0sXTOXVJ5nHgstR8t69sShGd+kMXUh5pYWPuJtMxbtnwxELY/x0SyEL3RpSSUxSv8se+CM56pdN5ugy0v6dRnKwJP4kfk68M+ssP63+7jr1Z0Pef5ywsgPsMMk67TLqlhN5bKIVUAcuE2wDkmFIg26tO9XQPXgGCoGtFkfun2Ra8tCG7Txq2838DAR7M9MiV3/jUmJ+Y0h06pGf/1K2LrwnaG58pzodEApvIrwneiO2pQaltaFotUA/CTpkRLiJk+1pUnXlf9Y6TOAL/r7lVvLd0l8s9AstipsNg+6L7SQRVcFn0ib2DsI=
before_install:
- mkdir -p $HOME/.local/bin
install:
- true
script:
- curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1
  -C ~/.local/bin '*/stack'
- stack --version
- sed -i 's@\$HOME@'"$HOME"'@' TexLive.profile
- cat TexLive.profile
- wget http://mirror.ctan.org/systems/texlive/tlnet/install-tl-unx.tar.gz
- wget https://github.com/scottkosty/install-tl-ubuntu/raw/master/debian-control-texlive-in.txt
- wget http://ftp.cs.stanford.edu/tex/bibtex/apalike.sty
- tar zxf install-tl*
- "./install-tl*/install-tl -profile TexLive.profile"
- export PATH=$PATH:$HOME/texlive/bin/x86_64-linux
- "./install-more-tl-pkgs.sh"
- mv apalike.sty ~/texlive/texmf-dist/tex/latex/
- mktexlsr
- tar zcf texlive.tar.gz -C ~ texlive
- equivs-build debian-*
- mv texlive-local*.deb texlive-local.deb
- mkdir dist
- mv texlive.tar.gz texlive-local.deb dist/
- "./index.sh > dist/index.html"
cache:
  directories:
  - "$HOME/.ghc"
  - "$HOME/.cabal"
  - "$HOME/.stack"
deploy:
  provider: releases
  api_key:
    secure: FzHnYT5YS73gJ7AvwK6KqvZWlQWvyZb9TyjPFUd53/jXwUrwisH9VOycav0vmY/mU4DYw6oXTVQaj3KCQJqWw3x9+lg8USa89p8upueTzSb9fIV1N+t/9eeFDlHY/F1xGobAFAm80iy2IQx1CifSEr9faik0jkt+jCZzuYogzbqqMyMr1LE5gMN3VQyiOzZKPrh2BfW+iT+D+XssAoemVi27B9bTu3SccalG73J8cvjQhb0rQTJgFp5tBAM7Bh6Q5r+Ir2MA8MGnPnKM1huMfLJjPNFap3oTvPA0ypA9ndwwM7SyP2B+IuerrH3ZuzFwnke8mfTQey/rXAh1cHWcOsE3TxfG48chqG52sy5zPH2K1o1ERNE1boBqQBRewOizuROpInSl+iGSHdUsJsdmvX/AbIB89oqYC+BZ8wLU6vqW0KJ1vwehQ+Vxxli/Bg2jdu/udGWVpGEaW6pl8B9h0QavOIZnhVbMP9c/UebAkekz4u9u1VBpE1LWAqRY8mNaqCKitv9r/3fWWI/+dS1uS2eR5N3pAccF8R8tjOvOA4bAUA+nT11hZQSHgl6d0UDpdMb29Ntz55tGtXSWOnWfH0QZbRoqTMyapln93ZU/kOEfCU7qIPcwrCWJfQYGKMFy8m+tVKIvoYXLou2F6dSKIkFlHqv6bwAoPFJ8R42Xbq0=
  local_dir: dist
  file: 
    - dist/texlive-local.deb
    - dist/texlive.tar.gz
  on:
    repo: HughParsonage/travis-bin
