language: c

env:
  - PATH=$PATH:$HOME/.cabal/bin

before_install:
  - export TARGET="$(git log --format=%B --no-merges -n 1 | grep -E "\[build .+\]" | sed 's/.*\[build \(.*\)\].*/\1/')"

install:
  - "[ -z $TRAVIS_TAG ] || exit 0"
  - sudo apt-get update
  - ./install"

script:
  - "[ -z $TRAVIS_TAG ] || ./build"

deploy:
  provider: releases
  api-key:
    secure: "Lf3cMSpdhZ/2Xd4U1ty+uycfhuYaBylOJMBmSkiIkUoVVsIA51wGCfCwDV4+5vaCnWISmHGBcdzi5uLsRdN/0FyVjP9py5edrJdgX4OQJTozfalB+fz4P4zdaMDdnvQgEsSDez4O8sHoHAhkz0K9I+zVswGlpD/+3udqIohdxTo="
  file:
    - pandoc*
    - texlive*
  file_glob: true
  skip_cleanup: true
  on:
    tags: true
    all_branches: true
