language: haskell
dist: trusty
sudo: false

addons:
  apt:
    packages:
    - equivs
    - python
    - pandoc-citeproc

env:
  global:
    - PATH=$HOME/.local/bin:$PATH

before_install:
  - mkdir -p $HOME/.local/bin

install:
  - ./install

script:
  - ./build

cache:
  directories:
  - $HOME/.stack

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GH_TOKEN
  local_dir: ~/.local/bin
  on:
    branch: master
